blog/apps/post/urls.py
from django.urls import path
from . import views  # importamos las vistas de la app post


app_name = "post" # le damos un nombre a la app para evitar hardcodear en los templates


urlpatterns = [
    #path("", views.index, name="index"), 
    path('ver_post/<int:post_id>/', views.ver_post, name='ver_post'),
    path('post_list/', views.post_list, name="post_list"),
    path('crear_post/', views.crear_post, name='crear_post'),
    path('editar_post/<int:id>/', views.editar_post, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_post, name='eliminar_post'),
    #path('realizar_comentario/<int:post_id>/', views.realizar_comentario, name='realizar_comentario'),
    #path('<int:post_id>/comentar/', views.realizar_comentario, name='realizar_comentario'),
    path('post/<int:post_id>/comentar/', views.realizar_comentario, name='realizar_comentario'),
    path('mostrar_categorias/', views.post_list, name='mostrar_categorias'),
    path('contact/', views.contact_form, name='contact_form'),
    path('buscar/', views.filtered_publications, name='buscar_posts'),


   
    ]

blog/apps/user/urls.py
from django.urls import path
from . import views  

app_name = "user" 
urlpatterns = [
    path("login/", views.loginUser, name="login"),
    path("profile/<int:id>", views.profile, name="profile"),
    path("register/", views.registerUser, name="register"),
    path("logout/", views.logoutUser, name="logout"),
    path("changePassword/", views.changePassword, name="changePassword"),
    path('modificar_contrasena/', views.changePassword, name='modificar_contrasena'),
    path('recuperar_contrasena/', views.recuperar_contrasena, name='recuperar_contrasena'),
    path('confirmar_recuperar_contrasena/', views.confirmar_recuperar_contrasena, name='confirmar_recuperar_contrasena'),
    ]  

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"), #pagina principal
    path("about/", views.about, name="about"), #pagina de about
    path("user/", include("apps.user.urls")), #apartado de login
    path("post/", include("apps.post.urls")), #apartado de post
    ## Password Reset ### https://www.youtube.com/watch?v=y-4-qv9_zP8
    #tiene un input de email para enviar el link de reseteo de contraseña
    path("reset_password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    #envia el link de reseteo de contraseña al email y muestra un mensaje de que se envio correctamente
    path("reset_password_send", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    #tiene identificador de usuario y token para resetear la contraseña
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #muestra el mensaje de que la contraseña se reseteo correctamente
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('post/', include('apps.post.urls', namespace='post')),
] 
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1 class="text-info">Los Nuevos Pythoneers</h1>
    <p>Este blog de noticias fue el proyecto final de la Etapa 2 del Informatorio</p>
    <div class="d-flex justify-content-around mt-5">
       <section class="d-flex flex-column">
        <p>Los nuevos Pythoneers está conformado por:</p>
        <ul>
                      
            <li class="list-group-item my-4">
                <h4>Néstor Gustavo Palacios Meyer</h4>
                <img src="{% static '../media/src/gustavo.jpg' %}" alt="about" width="300px">
            </li>
         
            <li class="list-group-item my-4">
                <h4>Julio Pablo Federico Bazan</h4>
                <img src="{% static '../media/src/fede.jpg' %}" alt="about" width="300px">
            </li>
            <li class="list-group-item my-4">
                <h4>Daira Cuquejo</h4>
                <img src="{% static '../media/src/daira.jpeg' %}" alt="about" width="300px">
            </li>
            
        </ul>
       </section>
       <section>
        <div class="d-flex justify-content-around mt-5">
           
       
        </div>
      
       </section>
    </div>

</div>
{% endblock %}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es-ar" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_styles %}{% endblock extra_styles %}
    <title>{% block title %}Pythoneers Noticias{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'logo/News_icon-icons.com_74697.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'Bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Bootstrap/css/style.css' %}">
    <link href="{% static 'Bootstrap/css/clean-blog.min.css' %}" rel="stylesheet">
</head>
<body>

    {% include "header.html" %}
    <div id="content" class="bg-dark d-flex align-items-center justify-content-center container">
        {% block content %}{% endblock content %}
     
    
    </div>
    {% include "footer.html" %}
    {% block extra_js %}{% endblock extra_js %}
   
    <script src="{% static 'Bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'Bootstrap/js/clean-blog.min.js' %}"></script>
</body>
</html>

blog/templates/buscar_posts.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ titulo }}</h2>
   
    
    {% if publicaciones %}
        <ul>
            {% for publicacion in publicaciones %}
            <h1>{{ publicacion.titulo }}</h1>
            <li>{{ publicacion.contenido }}</li>
            <li>{{ publicacion.resumen }}</li>
            <li>{{ publicacion.fecha_creacion }}</li>
            <li>{{publicacion.autor}}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No se encontraron publicaciones que coincidan con el filtro.</p>
    {% endif %}
    <div>
       <input type="hidden" name="separador"> 
    </div>
{% endblock %}

blog/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if message_sent %}
        <div class="alert alert-success">
            Gracias por contactarnos. Tu mensaje ha sido enviado correctamente.
        </div>
    {% else %}
        <h2 class="text-center text-info">Formulario de Contacto</h2>
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Nombre:</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Mensaje:</label>
                    <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Enviar mensaje</button>
            </form>
        </div>
    {% endif %}
{% endblock content %}

blog/templates/footer.html
<footer id="footer" class="container-fluid">
    <div class="d-flex justify-content-around align-items-center">
        <span class="text-center">&copy; 2023 Pythoneers. Todos los derechos reservados.</span>
        <div class="d-flex align-items-center">
            <span class="me-3">Nuestras redes</span>
           
            <div class="d-flex gap-3">
                <a href="https://www.facebook.com/" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/" target="_blank">Instagram</a>
                <a href="https://www.twitter.com/" target="_blank">Twitter</a>
            </div>
        </div>
    </div>
</footer>

blog/templates/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg bg-dark d-flex" id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'logo/pyy.png' %}" style="width: 120px;" ></a>
      {% comment %} boton del nav en mobile {% endcomment %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% comment %} menu del nav {% endcomment %}
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %} ">Sobre nosotros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:post_list' %}">Publicaciones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:contact_form' %}">Contacto</a>
          </li>
           
          </li>
        </div>
        {% comment %} ####IMPORTANTE#### {% endcomment %}
        {% if request.user.is_authenticated and request.user.userprofile.is_collaborator %}
        <button>
          crear post
        </button>
        
        {% endif %}

        {% comment %} opciones de usuario {% endcomment %}
        <div class="" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              {% if request.user.is_authenticated %}
                  <a class="nav-link disable" aria-current="page" href="{% url 'user:logout' %}">Cerrar sesión</a>
              {% else %}
                  <a class="nav-link active link-info" aria-current="page" href="{% url 'user:login' %}">Iniciar sesión</a>
              {% endif %}
            </li>
              {% if not request.user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link link-info" href="{% url 'user:register' %}">Registrarse</a>
                  </li>
              {%endif%}
              
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link link-info" href="{% url 'user:profile' request.user.id %}"> {{request.user.username|capfirst}}</a>
              </li>
              {% endif %}
          </ul>
        </div>
      </div>
        </ul>
  </nav>
</header>

blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block headers %}



{% endblock %}
<div class="container">
{% if user.is_authenticated %}
<h1 style="color: rgb(238, 232, 232);Text-align:center;">Bienvenidos al Sitio Web</h1>
<div class="d-flex justify-content-center mt-3">
  
  <a href="{% url 'post:crear_post' %}" class="btn btn-outline-info">¿Deseas crear una publicación?</a>
</div>

{% else %}
<div class="d-flex justify-content-center mt-3">
  <a href="{% url 'user:login' %}" class="btn btn-outline-info">Iniciar sesión para crear una publicación</a>
</div>
{% endif %}

<div class="d-flex justify-content-center mt-5 accordion">
  <button class="btn btn-outline-info" type="submit"><a href="{% url 'post:post_list' %}">Ver todos los posteos</a></button>
  

  
</div>
  <div>
    <br>
    <h2>Una pequeña ciudad llamada Cognópolis</h2>
<p>Había una vez una pequeña ciudad llamada Cognópolis, donde la inteligencia artificial (IA) había dejado de ser solo un concepto futurista para convertirse en una herramienta cotidiana y valiosa para sus habitantes. En Cognópolis, la IA estaba integrada en cada aspecto de la vida diaria, desde el transporte hasta la atención médica y la educación.</p>
<br>
<p>Un día, Lucas, un joven apasionado por la tecnología, llegó a la ciudad en busca de oportunidades para realizar su sueño de ser inventor. Al explorar las calles, se maravilló al ver la forma en que la IA estaba en todas partes, mejorando la eficiencia y la calidad de vida de sus habitantes. Decidió que quería aprender más sobre esta fascinante tecnología y se matriculó en la Universidad de Cognópolis, famosa por sus programas de IA.</p>
<br>
<p>En la universidad, Lucas se sumergió en el mundo de la inteligencia artificial, aprendiendo cómo las máquinas podían analizar grandes cantidades de datos para tomar decisiones informadas y predecir situaciones futuras. Descubrió cómo la IA impulsaba avances en áreas como la medicina, donde los diagnósticos y tratamientos eran más precisos y personalizados, y en la ecología, donde ayudaba a proteger el medio ambiente.</p>
<br>
<p>Un día, mientras participaba en un proyecto de investigación sobre energías renovables, Lucas encontró un antiguo molino de viento abandonado en las afueras de la ciudad. Comenzó a preguntarse si podría revivir esa tecnología con la ayuda de la IA. Entonces, se dedicó en cuerpo y alma a convertir el molino en una fuente de energía limpia y sostenible.</p>
<br>
<p>Con el apoyo de sus profesores y compañeros, Lucas diseñó un sistema inteligente que ajustaba la posición de las aspas del molino en función de los datos climáticos y la demanda de energía. La IA también permitía detectar fallos y realizar mantenimiento preventivo, garantizando el óptimo funcionamiento del molino en todo momento.</p>
<br>
<p>La noticia de su proyecto se difundió rápidamente por la ciudad, y pronto el molino de viento se convirtió en un símbolo del poder transformador de la inteligencia artificial. La gente comenzó a comprender aún más la importancia de utilizar herramientas de IA en la resolución de problemas, no solo en términos de eficiencia, sino también en la contribución a un mundo más sostenible y consciente.</p>
<br>
<p>La historia de Lucas y su molino de viento inspiró a otros jóvenes de Cognópolis a embarcarse en carreras en tecnología e inteligencia artificial. Con el tiempo, la ciudad se convirtió en un centro de innovación y desarrollo de IA, atrayendo a talentos de todo el mundo.</p>
<br>
<p>Y así, gracias al ingenio y la pasión de Lucas, Cognópolis demostró que la inteligencia artificial no era solo una herramienta, sino una aliada poderosa para la creación de un futuro mejor. Al integrar la IA en sus vidas, los ciudadanos aprendieron que, con un enfoque ético y responsable, podían lograr avances extraordinarios que beneficiaban a toda la humanidad. La inteligencia artificial se convirtió en un faro de esperanza, iluminando el camino hacia un mundo más inteligente y sostenible para todos.</p>
  </div>
</div>
{% endblock content %}

blog/templates/welcome.html
{% load static %}
{% block content %}
<p>hola?</p>

{% endblock content %}