blog/apps/post/urls.py
from django.urls import path
from . import views  # importamos las vistas de la app post


app_name = "post" # le damos un nombre a la app para evitar hardcodear en los templates


urlpatterns = [
    #path("", views.index, name="index"), 
    path('ver_post/<int:post_id>/', views.ver_post, name='ver_post'),
    path('post_list/', views.post_list, name="post_list"),
    path('crear_post/', views.crear_post, name='crear_post'),
    path('editar_post/<int:id>/', views.editar_post, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_post, name='eliminar_post'),
    #path('realizar_comentario/<int:post_id>/', views.realizar_comentario, name='realizar_comentario'),
    #path('<int:post_id>/comentar/', views.realizar_comentario, name='realizar_comentario'),
    path('post/<int:post_id>/comentar/', views.realizar_comentario, name='realizar_comentario'),
    path('mostrar_categorias/', views.post_list, name='mostrar_categorias'),
    path('contact/', views.contact_form, name='contact_form'),
    path('buscar/', views.filtered_publications, name='buscar_posts'),


   
    ]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"), #pagina principal
    path("about/", views.about, name="about"), #pagina de about
    path("user/", include("apps.user.urls")), #apartado de login
    path("post/", include("apps.post.urls")), #apartado de post
    ## Password Reset ### https://www.youtube.com/watch?v=y-4-qv9_zP8
    #tiene un input de email para enviar el link de reseteo de contraseña
    path("reset_password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    #envia el link de reseteo de contraseña al email y muestra un mensaje de que se envio correctamente
    path("reset_password_send", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    #tiene identificador de usuario y token para resetear la contraseña
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #muestra el mensaje de que la contraseña se reseteo correctamente
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('post/', include('apps.post.urls', namespace='post')),
] 
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from apps.user.models import UserProfile


class Categoria(models.Model):
    titulo = models.CharField(max_length=100, unique=True, null=False)
    nombre = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.titulo
    
class Post(models.Model):
    titulo = models.CharField(max_length=200, unique=True, null=False)
    contenido = models.TextField(null=False)
    resumen = models.TextField(max_length=600, null=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="media/post/publicado", default="media/post/default/default.jpg")
    publicado = models.BooleanField(default=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha_actualizacion = models.DateTimeField(auto_now=True, null=True)
    permitir_comentarios = models.BooleanField(default=True)
    def __str__(self):
        return self.titulo

    class Meta:
        ordering = ["-fecha_creacion","-fecha_actualizacion", "categoria"]  

    def __str__(self):
        return self.titulo
    
    def delete(self, *args):
        self.imagen.delete()
        super().delete(*args)


class Comentario(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField(null=False)
    fecha_creacion = models.DateField(auto_now_add=True, null=True)
    fecha_actualizacion = models.DateField(auto_now=True, null=True)


    class Meta:
        ordering = ["-fecha_creacion","-fecha_actualizacion"]

    def __str__(self):
        return self.contenido
    

blog/apps/post/forms.py
from django import forms
from .models import Comentario, Post

class FormularioComentario(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']
        widgets = {
            'contenido': forms.Textarea(attrs={'rows': 4}),  # Para darle un tamaño adecuado al campo de contenido
        }

        
class CrearArticuloForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['fecha_actualizacion'] 
        
class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']               
        
        

blog/apps/post/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Categoria, User, Comentario
from .forms import ComentarioForm, PostForm
from django import forms
#from apps.post.forms import publicacionForm ##donde esta publicacionForm??? D:
from django.forms import modelform_factory
from django.core.paginator import Paginator
from datetime import date
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    # Obtener los últimos posteos
    posts = Post.objects.order_by('-fecha_publicacion')[:5]
    
    return render(request, 'post/index.html', {'posts': posts})

    
def categorias(request):
    return render(request, 'categorias.html')


def ver_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comentarios = post.comentario_set.all()#trae todos los comentarios de este post en particular
    context = {
        'publicacion': post,
        'comentarios': comentarios,
    }
    return render(request, 'post/post_detail.html', context) #crear html de post

#USAR PAGINADO CON PAGINATOR
   
def post_list(request):
  
    posts = Post.objects.all()
    comentarios = Comentario.objects.all()
    
   
    context = {
        'post': posts,
        'comentarios': comentarios,
        
    }

    return render(request, 'post/post_list.html', context)

def post_list2(request):
    categorias = Categoria.objects.all()
    query = request.GET.get('q')
    categoria_id = request.GET.get('categoria')

    if query:
        posts = Post.objects.filter(titulo__icontains=query)
    elif categoria_id:
        posts = Post.objects.filter(categoria_id=categoria_id)
    else:
        posts = Post.objects.all()

    context = {
        'posts': posts,
        'categorias': categorias,
    }
    return render(request, 'post/post_list.html', context)

# @login_required
# def crear_post(request):
#     publicacionForm = modelform_factory(Post, exclude=['fecha_actualizacion'])
#     if request.method == 'POST':
#         formPost = publicacionForm(request.POST)
#         if formPost.is_valid():
#             post = formPost.save(commit=False)  # Guardamos el formulario sin guardar en la base de datos aún.
#             post.autor = request.user  # Asignamos el autor al usuario actualmente autenticado.
#             post.save()  # Ahora guardamos la publicación en la base de datos.
#             #print(post.id)
#             #return redirect('ver_post', post.id)  # Redirigir a la página de ver_post.
#     else:
#         formPost = publicacionForm()   
#     return render(request, 'post/new_post.html', {'formPost': formPost})

# @login_required
# def crear_post(request):
#     if request.method == 'POST':
#         formPost = PostForm(request.POST)
#         if formPost.is_valid():
#             post = formPost.save(commit=False)
#             post.autor = request.user
#             post.save()
#             return redirect('ver_post', post_id = post.id)
#     else:
#         formPost = PostForm()
#     return render(request, 'post/new_post.html', {'formPost': formPost})

# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         exclude = ['fecha_actualizacion']
@login_required
def crear_post(request):
    if request.method == 'POST':
        formPost = PostForm(request.POST)
        if formPost.is_valid():
            post = formPost.save(commit=False)
            post.autor = request.user
            post.save()
            #return redirect('post_list')
            return redirect('post:ver_post', post_id=post.id)
             # Use the name of the URL pattern and pass the 'post_id'
    else:
        formPost = PostForm()
    return render(request, 'post/new_post.html', {'formPost': formPost})

@login_required
def editar_post(request, id):
    publicacion = get_object_or_404(Post, pk=id)
    publicacionForm = modelform_factory(Post, exclude=['fecha_actualizacion'])
    
    if request.method == 'POST':
        formPost = publicacionForm(request.POST, instance=publicacion)
        if formPost.is_valid():
            formPost.save()
            return redirect('post:post_list')  # Usamos post_id en lugar de id
    else:
        formPost = publicacionForm(instance=publicacion)
        
    return render(request, 'post/update_post.html', {'formPost': formPost})


@login_required
def eliminar_post(request, id):
    publicacion = get_object_or_404(Post, pk=id)
    if (request.user == publicacion.autor ):
        if request.method == 'POST':
            publicacion.delete()
            return redirect('post:post_list')
    else:
        return redirect('index')     
    return render(request, 'post/delete_post.html',{'publicacion':publicacion})

 


def realizar_comentario(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comentarios = Comentario.objects.filter(post=post)
    
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.post = post
            comentario.autor = request.user
            comentario.save()
            return redirect('post:post_list')
           
    else:
        form = ComentarioForm()

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'post/realizar_comentario.html', context)

def contact_form(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

       
        send_mail(
            'Formulario de contacto - ' + name,
            'Email: ' + email + '\nMensaje: ' + message,
            'project_manageer@protonmail.com',  
            ['project_manageer@protonmail.com'],  
            fail_silently=False,
        )

  
        return HttpResponseRedirect(reverse('contact_form', kwargs={'message_sent': True}))
    
 
    return render(request, 'contact.html', {'message_sent': False})



def filtered_publications(request):
    filter_term = request.GET.get('filter', '')  
    filtered_publications = Post.objects.filter(titulo__icontains=filter_term)

    context = {
        'publicaciones': filtered_publications,
        'titulo': f'Publicaciones con título que contiene "{filter_term}"',
        
    }

    return render(request, 'buscar_posts.html', context)

blog/templates/post/delete_post.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="d-flex flex-column align-items-center justify-content-between px-4 pt-4 pb-3 rounded-4 form-control border-info w-auto">
    <h2>¿Estás seguro de que deseas eliminar la publicación?</h2>
    <table>
        <form method="POST" enctype="multipart/form-data" action="{% url 'post:eliminar_post' publicacion.id %}">
            {% csrf_token %}   
            {{ formPost }} 
            <button class="btn btn-outline-info" type="submit">Confirmar eliminación</button>
        </form>
    </table>
</div>

{% endblock content %}

blog/templates/post/new_post.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="d-flex flex-column align-items-center justify-content-between px-4 pt-4 pb-3 rounded-4 form-control border-info w-auto">
    <h1>Crear Publicacion</h1>
    <form method="POST">
        {% csrf_token %}

        {{ formPost.as_p }}

        <button class="btn btn-outline-info" type="submit">Crear Publicacion</button>

    </form>

</div>

{% endblock content %}

blog/templates/post/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Se debe crear como new post un boton para comentar y agregar un cuadro de texto donde ira el comentario, no olvidar crsf-token-->



{% endblock %}

blog/templates/post/post_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div  class="flex-container">
    <br>
</div>
    <div class="text-center">
        <br>
        <form action="{% url 'post:buscar_posts' %}" method="get" style="position: absolute!important;">
            <input type="text" name="filter" placeholder="Buscar posts...">
            <button type="submit" class="btn btn-primary">Buscar publicación</button>
        </form>
        <br>
        <br>
        {% for p in post %}
        <h1>{{ p.titulo }}</h1>
        <li>{{ p.contenido }}</li>
        <li>{{ p.resumen }}</li>
         <li>Autor de la publicación: {{p.autor}}</li>
        <img src="{{ p.imagen.url }}" alt="{{ p.titulo }}" width="200">
        <li>{{ p.fecha_creacion }}</li>
        
        {% if user.is_authenticated and p.autor == user %}
            <a href="{% url 'post:editar_post' id=p.id %}" class="btn btn-outline-info">Editar esta publicación</a>
            <a href="{% url 'post:eliminar_post' id=p.id %}" class="btn btn-outline-danger">Eliminar esta publicación</a>
        {% endif %}
        
        <div>
            <h4>Comentarios:</h4>
            <ul>
                {% for comentario in comentarios %}
                    {% if comentario.post.id == p.id %}
                       
                            <p><strong>{{ comentario.autor }}</strong>: {{ comentario.contenido }}</p>
                            <p>Fecha de creación: {{ comentario.fecha_creacion }}</p>
                        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    
        {% if user.is_authenticated %}
            <!-- Formulario para agregar un comentario a esta publicación -->
            <form method="post" action="{% url 'post:realizar_comentario' post_id=p.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Comentar</button>
            </form>
        {% endif %}
        {% endfor %}
     
   
    </div>
    
    <div>
        <input type="hidden" name="separador"> 
     </div>
   
{% endblock %}

blog/templates/post/realizar_comentario.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h1>Realizar Comentario</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Comentar</button>
</form>

{% endblock %}

blog/templates/post/update_post.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    
<div class="d-flex flex-column align-items-center justify-content-between px-4 pt-4 pb-3 rounded-4 form-control border-info w-auto">
    
    <table>
        <form method="post">
            {% csrf_token %}
            {{ formPost.as_p }}
            <button type="submit">Guardar cambios</button>
          </form>
    </table>
</div>

{% endblock content %}